[package]
name = "fjord-cli"
version = "0.1.0"
authors = ["maedana <maeda.na@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seahorse = "*"
termion = "*"
open = "*"
